### ISSUE TITLE
用词错误

### ISSUE THREAD

**Issue by wildck** [JinMuInfo/MongoDB-Manual-zh#5]
https://hbn-king.gitbook.io/mongodb-manual-zh/indexes

原文:
You cannot drop this index on the _id field.

现有译文:
您不能将此索引放在字段上。

建议翻译:
你不能将_id字段上的index删除。

--------------------------------------------

原文:
Other than the unique constraint, unique indexes are functionally interchangeable with other MongoDB indexes.

现有翻译:
除了唯一约束之外，唯一索引在功能上可以与其他MongoDB索引互换。

建议翻译:
除了唯一性约束，唯一索引和MongoDB其他索引功能上是一致的。

--------------------------------------------

原文:
By indexing a subset of the documents in a collection,

现有翻译:
通过索引集合中文档的子集

建议翻译:
通过对集合中的部分文档建立索引，

--------------------------------------------

原文:
You can combine the sparse index option with the unique index option

现有翻译:
可以将稀疏索引选项与惟一索引选项结合使用

建议翻译:
可以将稀疏索引与唯一索引结合使用

--------------------------------------------

原文:
Indexes and Collation

现有翻译:
索引和排序规则

建议:
collation的翻译有误，及其该章节下的样式也有问题，建议整改

--------------------------------------------

原文:
When the query criteria and the projection of a query include only the indexed fields

现有翻译:
当查询条件和查询的投影只包含索引字段时

建议:
可以将翻译起来不流畅的单词采用 <> 备注的方式来翻译,例如:

当查询条件和查询的投影<projection>只包含索引字段时

--------------------------------------------

原文:
see Index Builds on Populated Collections, including the Index Builds in Replicated Environments section

现有翻译:
请参见 “填充集合上的索引构建”，包括“ 复制环境中的 索引构建”部分。

建议翻译:
请参见 "现存集合的索引构建"，包括"在复制集环境下的索引构建"章节

**Comment by ys17513628804** [comment]
已修改
