### ISSUE TITLE
文件路径不兼容Windows的bug

### ISSUE THREAD

**Issue by snomiao** [JinMuInfo/MongoDB-Manual-zh#51]
![image](https://user-images.githubusercontent.com/7323030/95729005-cb532a00-0cae-11eb-871b-963ac28b81cd.png)
Windows环境下clone出错，原因是windows下路径不能有冒号，而 `docs/15-Storage/FAQ:MongoDB-Storage.md` 里有个冒号

不太清楚官方MongoDB手册的网址会不会有冒号

我比较建议的现成解决方案是用短横代替 `-` 掉有冒号名字的文件和目录的冒号。

而长远考虑的话建议直接照官方网址 `https://docs.mongodb.com/manual/` 爬取，并自动生成一套相同的文档路径，然后单个文档内部再一对一翻中。

以上。

**Comment by ys17513628804** [comment]
首先，感谢您提出的BUG和提供给我们的建议，目前已经解决了这个路径的BUG，已经将docs/15-Storage/FAQ:MongoDB-Storage.md中的“：”改为了“-”，现在可以放心将文件下载下来。
